title: "Sainath Manda"
email: "sainathmanda777@gmail.com"
description: "Portfolio of Sainath Manda"
baseurl: ""
url: "https://sainathmanda7.github.io"
github_username: "sainathmanda7"
linkedin_username: "sainath-manda"
